default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: postgres
  # password: frank1738

development:
  <<: *default
  database: Library_development

test:
  <<: *default
  database: Library_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"]%>
